### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by jcmousse**
create a fr.js file

### CODE REVIEW

**Comment by psi-4ward** [comment]
There is no fr.js and you are not allowed to change the config.js

**Comment by jcmousse** [comment]
Sorry i'm not comfortable with git and the pr.
I didn't mean to modify config.js.
Now fr.js is ready, i committed and pushed it in the right place.
Still, i don't know how to get rid of the "wrong" config.js :(


Le 14/12/2020 à 22:53, Christoph Wiechert a écrit :

**Comment by psi-4ward** [comment]
Copy the latest version of this version to your fork and commit it again

**Comment by jcmousse** [comment]
I think i did it, #134. Well, I hope so.
Thanks for your patience :)

Le 14/12/2020 à 23:20, Christoph Wiechert a écrit :

**Pull request closed without merging**
