### PR TITLE
NL translation

### PR DESCRIPTION
**Pull request by jicho**

### CODE REVIEW

**Comment by stefanvangastel** [comment]
Duplicate of #148 :D

**Comment by psi-4ward** [comment]
can you guys solve this and close one PR pls?

**Comment by stefanvangastel** [comment]
I'll close mine. Since it's older.

**Comment by psi-4ward** [comment]
Close the one who is less good :D

**Comment by jicho** [comment]
Looks like the problem has been solved.
I missed the Dutch translation completely when I was looking at the open issues, sorry...

**Comment by mariusvw** [comment]
Updated some minor typo's in PR #185

**Pull request closed without merging**
