### PR TITLE
Create Portuguese translation

### PR DESCRIPTION
**Pull request by bhbarbosa**
Hi!

Not sure about langCode though, but this is Brazilian Portuguese translation.

### CODE REVIEW

**Comment by jcmousse** [comment]
Hello,

I am very happpy with psitransfer, and i'm ready to provide a french translation.
Right now, i'm testing the change of the default language on my present psitransfer 
docker setup.

In the docker-compose file, i add
PSITRANSFER_DEFAULT_LANGUAGE=pt
to the environment section, but the web interface sticks to english language.

What am i doing wrong ?

Regards,
jeanclaude

Le 12/11/2020 à 19:47, Bruno Henrique Barbosa a écrit :

**Comment by psi-4ward** [comment]
Please inspect your accept lang header

**Comment by jcmousse** [comment]
Done!
Didn't know it was "automatic". Great job!

The fr.js file is ready, how do i add it to the lang directory ?

Thanks for your time.
jc


Le 14/12/2020 à 22:11, Christoph Wiechert a écrit :

**Comment by psi-4ward** [comment]
pls create PR :)

**Pull request merged**
