### PR TITLE
Implement chunk size option, QR Code and URL shortener button and rework user interface

### PR DESCRIPTION
**Pull request by Haocen**
Problem description:
I noticed some web application firewall explicitly set max request body size but tus failed to handle such situation properly, instead the upload was resumed from very beginning since client consider unknown error a completely failed request.

Fix implemented:
2 new options are added, one will allow the chunk size to be controlled from server, meanwhile another option will allow chunk size to be modified from web UI for each upload, by the uploader.

### CODE REVIEW

**Comment by Haocen** [comment]
Implemented QR Code.
Ref:
https://github.com/psi-4ward/psitransfer/issues/15

**Comment by Haocen** [comment]
Reworked UI:
image

image

image

image

image

Inspired by:
https://codepen.io/Godje/pen/XdKaER

**Comment by psi-4ward** [comment]
looks not bad but putting everything in a single PR is really hard to merge. 
You should do one PR for each change so we can discuss und merge.

**Comment by Haocen** [comment]
Hi, thanks for the heads up.
What are the changes we want to prioritize?
Maybe start with the chunk size option?
I can definitely cherry-pick desired commits and create another PR, no problem.

**Comment by psi-4ward** [comment]
I'm on creating an enhanced version for a customer. Some of these changed will go into a new version as opensource:
* Subfolder deployment
* Chunking
* Pug Templates
* Multi-Lang
* Dependency updates

So would be better to wait until this is merged in the public upstream master. 
If this is done we can pick each of your suggestions and discuss (and probably merge) it one by one.

**Comment by Haocen** [comment]
Good to know, thanks.

**Comment by Haocen** [comment]
Waiting upstream to be updated.
Closing for now.

**Comment by psi-4ward** [comment]
Hey @Haocen, take look into the dev-branch. I've commited _some_ stuff.

I think I'm almost done with "new features" and we could discuss your additions. 

* Chunk-size: We should find a good fixed value. User-Setting would be to complicated for almost every uploader ;)
* QR-Code: I've added a button to display a qr-code image in a new tab, this could be a good way for sharing.
* URL-Shortener: Sorry, I dont like this addition cause in most use-cases nobody needs to "type" the URL.
* User-Interface restyle: Looks nice but in cooperate envs it could be to colorful. Probably we can this add as "theme" ?

**Comment by Haocen** [comment]
Hi,
Appreciate your getting back to me.

- For adding chunk size option and making it client configurable is simply given the fact my personal deployment serve people from all over the world and even with CDN and gslb in place, the sentry log I collected indicate upload successful rate may vary based on the chunk size. I'm investigating how to conduct automate connection stability and speed test and set the chunk size based on the result, it could be too complicated to be included, though.

 - URL shortener is mostly used for 3 purpose in my understanding, they are anti-scrapping, share to social media with message length limit(for example Twitter) and when you have to pass the link to the download vocally(there are phonetic URL shortener that will generate links like https://example.com/quick-fox-jumping)

 - The reworked user interface is intended to include all existing functionality, with some personal suggestion from an UX dev friend of mine, we can evaluate possible improvements if you wish. Meanwhile I'm not extremely familiar with Vue and it is unclear to me how to refactor the existing code into a theme, given some underlaying vuex store was modified to support the UI.

**Comment by Haocen** [comment]
I made a test deployment [here](https://upload.haocen.org/), please feel free to poke around and let me know your thoughts.

The filesystem is tiny & ephemeral, for obvious reasons.

**Pull request closed without merging**
