### PR TITLE
Add Download Button to File List

### PR DESCRIPTION
**Pull request by Alkl58**
Changed ZIP / TAR Icon
Hide ZIP / TAR Button when only one File - Fixes https://github.com/psi-4ward/psitransfer/issues/123
Fixed Icon Colors not matching in File List

Fixed Downloaded Checkmark not showing (Note that this could be the cause of a package update from https://github.com/psi-4ward/psitransfer/pull/212)

grafik

### CODE REVIEW

**Comment by psi-4ward** [comment]
I'm sorry but I need some more time to have a look.

**Comment by psi-4ward** [comment]
You have changed the indention of the template so seeing the diff is very hard. Could you fix this pls?

**Comment by Alkl58** [comment]
It has been 2 months. As far as I remember, I had to do these indention changes because of the updated pug package.

Will have to look into it again.

**Comment by psi-4ward** [comment]
Yes I apologize, didn't find any time. I've updated the deps and it looked good - pls check the current master.

**Comment by Alkl58** [comment]
Indention should be fixed now.

**Comment by DesktopMan** [comment]
Any chance this can be reopened? The changes in this PR are nice.

**Pull request closed without merging**
