### PR TITLE
Fixed IE11 download page link not working

### PR DESCRIPTION
**Pull request by alaincao**
'click()' function call doesn't open the link because the element is not added to the DOM #48

### CODE REVIEW

**Comment by lumbric** [comment]
I can confirm that this commit fixes the bug in Firefox 63.0 (Linux). Thanks a lot for the fix!  🎉

(Tested by rebuilding docker from this commit and running a new container.)

**Comment by psi-4ward** [comment]
Thanks for you PR!
Can you add a `aEl.style.display = 'none';` to be safe that we do not run into styling issues?

**Comment by psi-4ward** [comment]
Just add an comit it will update the pr

**Comment by alaincao** [comment]
Yes, thank you. But my commit clearly did not work, so I re-created it (#59) because I did not want to clutter your history with useless commits ...  
And Github wouldn't let me update this PR using a new branch. Sorry for that...

**Pull request closed without merging**
