### PR TITLE
Keycloak support

### PR DESCRIPTION
**Pull request by SmartBlug**
I like your tool. Easy to use and efficient !

I added support for keycloak.
I also created notion of guest when keycloak is used.
As Keycloak will require known user to use the service, this is possible to have a guest using the service for a certain amount of time (just press "create guest access" on upload page using retention period and password)
I also added a parameter : autoPassword that set password by default when set to true (you can still remove if you want).
/admin can track access and I added a "owner" to know who uploaded the file.
When this is a guest, this is registred as  "Guest of MrX"

You can try with docker smartblug/psitransfer

### CODE REVIEW

**Comment by tubalainen** [comment]
Ooowow - this is great. Hope that our code owner could parse this into a new release.

**Comment by atila01380** [comment]
Wowwwww so nice  we want this features !!!!

**Comment by martin-braun** [comment]
I'd love to see this merged, added and properly documented. Authentication is the very most this great product needs.

**Comment by psi-4ward** [comment]
This PR is outdated. If you think we need 3rd-party auth we should consider a more generic oauth2 approach?

**Pull request closed without merging**
