### PR TITLE
Changed the colors of the dark theme to more pleasant ones

### PR DESCRIPTION
**Pull request by lzrdblzzrd**
I couldn't change the color of the svg icons. Because of this, they do not look very nice on a dark background. If you change their color to a lighter one (It is desirable that the icons on the gray colors be #b9bbbe, and on the colors of the purple and green buttons - #ffffff), then everything should look beautiful.

### CODE REVIEW

**Comment by psi-4ward** [comment]
`fill` is the prop for svgs

but I still don't like the dark theme much and the whole bootstrap stuff could be replaced by some lighter definitions using css-vars

**Comment by lzrdblzzrd** [comment]
> `fill` is the prop for svgs

I don't really understand how to do this with css.


> but I still don't like the dark theme much and the whole bootstrap stuff could be replaced by some lighter definitions using css-vars

I will wait if you suddenly find a replacement for bootstrap, if anything, I can correct the colors if necessary.

**Comment by psi-4ward** [comment]
https://github.com/psi-4ward/psitransfer/blob/master/public/assets/styles.css#L295

I dont think I'll take the time to rewrite the CSS.

**Comment by lzrdblzzrd** [comment]
> https://github.com/psi-4ward/psitransfer/blob/master/public/assets/styles.css#L295
> 
> I dont think I'll take the time to rewrite the CSS.

Ah, got it. I will fix the icon colors soon.

**Comment by psi-4ward** [comment]
I think the colors are ok for now.

**Comment by lzrdblzzrd** [comment]
> I think the colors are ok for now.

image
These colors do not match the color scheme and look somehow out of tune. They should be light in order to be pleasant to look at. That's all that's left to change in colors, and I won't touch styles.css anymore

**Comment by psi-4ward** [comment]
Pls try the latest master

**Comment by lzrdblzzrd** [comment]
> Pls try the latest master: [ac18a15](https://github.com/psi-4ward/psitransfer/commit/ac18a15832023db19824368074f78cbbb0b12c3c)

Yes, everything looks really good now. Thanks.

**Pull request merged**
